### ISSUE TITLE
No slug displayed if term title is only emoji

### ISSUE THREAD

**Issue by kraftbj** [pento/x1f4a9#11]
If a term's title/slug contains an emoji, the edit-terms.php list table displays blank for the slug.

Within the db, it is in the `%f0%9f%9a` format.
![screen shot 2015-02-11 at 23 52 14](https://cloud.githubusercontent.com/assets/88897/6162457/11ff3910-b249-11e4-8811-637089fcc48d.png)

**Comment by helen** [comment]
@kraftbj I'm seeing this in places like permalink edit as well - could you make a Trac ticket for this instead, since it's in core trunk?

**Comment by kraftbj** [comment]
@helenhousandi Just came back to say the same thing. When I was testing initially, the actual emoji was displayed in the permalink and URL. On this saved draft, later published, the emoji was converted to HTML entities, which fail to display.

Core ticket: https://core.trac.wordpress.org/ticket/31328#ticket

Interestingly enough, yesterday, I was able to publish a post that saved the slug directly as the emoji—not in the HTML entity format—which did display in the admin correctly. Today, I can't seem to duplicate that behavior as it keeps converting it to HTML entities.

**Comment by kraftbj** [comment]
Yesterday's test. 
![screen shot 2015-02-13 at 22 33 52](https://cloud.githubusercontent.com/assets/88897/6198571/7a361520-b3d0-11e4-8ec6-29823f0c2295.png)

The "watch" post that seemed to save as emoji and the one that didn't (from wp_posts table):
![screen shot 2015-02-13 at 22 36 04](https://cloud.githubusercontent.com/assets/88897/6198574/c552597e-b3d0-11e4-80a0-bfe91df8b89d.png)

I'll see if I can duplicate the behavior and discuss in Trac as needed.

**Comment by pento** [comment]
Closing this ticket, it'll be fixed in [WP31328](https://core.trac.wordpress.org/ticket/31328).
