### ISSUE TITLE
Font styles and weights

### ISSUE THREAD

**Issue by peterwilsoncc** [pento/x1f4a9#19]
Dream coding thoughts on e736c8939f8d3f137121ed70c43d87c16ed2683c

The issue here is that browsers need to display the font as unitalic, unbolded regardless of the author's settings. Is it worth setting up an array to test against?

``` javascript
fontTests = ['600 Arial 32px', 'italic 600 Arial 32px', 'italic Arial 32px', 'Arial 32px']
// loop through array
// break on first failure
```

I'll do some testing this-weekend to see if it needs to be two loops to prevent layout thrashing. I'm not sure how browsers deal with layout on elements that are not attached to the document.

Or the test remains a single test with `italic 600 Arial 32px`

Let me know your thoughts and I'll add a pull request if needs be.

**Comment by pento** [comment]
We really only need the bold test because Chrome is currently broken. Unless there are reports of native emoji rendering being broken in other browsers, or under other conditions, I'm inclined to leave it as is.
