### ISSUE TITLE
Wordpress unable to save after installing plugin

### ISSUE THREAD

**Issue by lassebunk** [pento/x1f4a9#20]
Thanks for this great plugin.
However, after installing the plugin, I'm unable to save posts after editing.
Any idea what could be wrong?
Thanks.

**Comment by pento** [comment]
Hi there!

This was an experimental plugin - the feature has been rolled into WordPress 4.2, which will be released later this month.

I'll be disabling this plugin soon, the best option is to wait for WordPress 4.2. :-)

**Comment by lassebunk** [comment]
Ok, thanks, wasnt aware of that. :+1:
