### ISSUE TITLE
alt text for replaced emoji

### ISSUE THREAD

**Issue by kraftbj** [pento/x1f4a9#6]
As Andrea (afercia) mentioned in today's chat, the alt text on replaced emoji is the emoji itself:

https://github.com/pento/x1f4a9/blob/master/twemoji/twemoji.js#L416

ref: https://wordpress.slack.com/archives/core/p1423691009003721

Reported upstream via twitter/twemoji/#41 .

**Comment by kraftbj** [comment]
https://github.com/twitter/twemoji/issues/41 since GH didn't hotlink the text.

**Comment by pento** [comment]
I'm inclined to agree with the conclusion of twitter/twemoji#41 - alt text is used by all other browsers for copy/paste, and there's no way for us to generate an aria-label from the client side. (Even doing it on the server side may not be a viable option - it would be quite slow.)

**Comment by pento** [comment]
I'm going with the conclusion of twitter/twemoji#41.
