### ISSUE TITLE
Emoji not rendered in forms

### ISSUE THREAD

**Issue by kraftbj** [pento/x1f4a9#7]
Generally, any form in /wp-admin/ will not render emoji in non-native browsers (tested in stable Chrome). Including but not limited to:
- Search Box
- Add Terms (Category, Tag, etc) forms
- Bulk Editor
- Quick Editor
- Widgets

**Comment by pento** [comment]
This is an unfortunate side effect of Chrome not supporting emoji natively. It's really only the TinyMCE editor that can use the image, everything else has to try and render it natively.

I do wonder if, when the browser can't render the emoji, there's a place for converting emoji to their HTML encoded equivalent. Feels pretty hacky, though.

**Comment by pento** [comment]
Not going to do the HTML encoding. It's a hack, and doesn't really help the user.
