### ISSUE TITLE
Emoji not rendered after ajax actions

### ISSUE THREAD

**Issue by kraftbj** [pento/x1f4a9#8]
Any ajax action that would display an emoji will not render it.

Example:
1. edit-terms.php to add a new cat/tag
2. Set the name of the new term to an emoji and save
3. New term is ajax'd into the top of the list table. Character box displayed.

After refreshing the page, emoji rendered as expected.

Add a listener to the JS to recheck after ajax inserts into the DOM?

**Comment by pento** [comment]
This'll be fixed in [WP31328](https://core.trac.wordpress.org/ticket/31328).
